name: Orchestrator

on:
  push:
    branches:
      - main

jobs:
  call-testing-pipeline:
    name: Testing
    uses: ./.github/workflows/test.yml
  call-deploy-pipeline:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
  call-release-pipeline:
    name: Release
    needs:
      - call-testing-pipeline
      - call-deploy-pipeline
    uses: ./.github/workflows/release.yml
    secrets: inherit